language: go

sudo: false

env:
  - GO111MODULE=on

go:
  - 1.13.x

cache:
  directories:
    - $HOME/gopath/pkg/mod

script:
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
