language: go

sudo: false

env:
  - GO111MODULE=on

go:
  - 1.13.x

cache:
  directories:
    - $HOME/gopath/pkg/mod

script:
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    secure: "XyZ2l0YkzdYfAr9Qd470YxUeiNu1BxTJpYWvxtQuqbOX2PHV9zMQSnVv1VeqCuh7i4VQm3PiaZwn5M9BoJ52m2rNoTA+aHGlkxPYleKb8mdHE0Oh74FwReHvyriJusPy2tx+5HTjtfh+9SxTcdXWB7GwZZulRzHVOqVZHSh6Vgp/czkMMXY6Lwpg0hkuSBYPe1qmkXtFG68VqFomVUrI80UZJBpTXNykDC9+x+pPn5EaAg6xgwLvZDWkLmzMuCLO2/mOo10pp/5j9kFkOMMN7vdtYRhbqTtfWhBF07BCTDB5cx6cPrLZCBd/A/kkoaBRJT8Ihb3U4IJiVA9VRkJo/XVzHWubhl5DzNSw1n1ERjoZ1Q5PxPcNR5UFhqkW6gf4IQjRX2zs0EBcWJ2CH2cFQDiD64HiVQPywm3B51nKjkvIM07kQtkgJFKu/pKE64mURUW1IDtMwTyUVmJSNoYf9xAG9aNOUrq5DACzK6Xs/xgFqx6avwEext/yycBMOvPjOIKm/voxQmQVHkHxIN1EXfuId27afsOLJNoGvKLA7luDBzeqJimy7wVLrD11k/UDYwpX5ryCC8jbgRlvODH6lnwFpSdN5YktQeCgjOY3s1ib4R5uApDioF90NRvtbnup9Tv8j6dXUS8g9ru4t2nh6bQ+3nijGZYQ3aslGvhsk3Q="
